services:
  traefik:
    image: traefik:v3.6
    command:
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--certificatesresolvers.le.acme.email=${MD_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=600s"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--log.level=INFO"
      - "--log.maxAge=14"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.headerLabels.useragent=User-Agent"

      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.6"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./dynamic:/dynamic:ro
      - logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${HOMELAB_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard-auth.priority=10"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certResolver=le"
      - "traefik.http.routers.dashboard.middlewares=authentik-middleware@file"
      - "traefik.http.routers.dashboard-auth.rule=Host(`traefik.${HOMELAB_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.dashboard-auth.priority=15"
      - "traefik.http.routers.dashboard-auth.service=authentik-default-outpost@file"
    env_file: "docker.env"
    networks:
      - proxy
    restart: always

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.4
    container_name: "crowdsec"
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/http-cve
      APPSEC_CONFIGS: crowdsecurity/appsec-default
      CUSTOM_HOSTNAME: crowdsec
      # We need to register one api key per service we will use
      BOUNCER_KEY_TRAEFIK: ${BOUNCER_KEY_TRAEFIK}
    volumes:
      - logs:/var/log/traefik:ro
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - ./crowdsec/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
      - /var/log/crowdsec/:/var/log/crowdsec/
    ports:
      - 127.0.0.1:8081:8080
      - 6060:6060
    labels:
      - "traefik.enable=false"
    networks:
      - proxy

networks:
  proxy:
    name: proxy

volumes:
  logs:
  crowdsec-db:
  crowdsec-config:
